credentials:
  usernames:
    admin1:
      name: Jakob Laurner
      password: '1234'
      person_doc_id: 5
    admin2:
      name: Janick Hoffmann
      password: '1234'
      person_doc_id: 4
    mmustermann:
      name: Max Mustermann
      password: passwort123
      person_doc_id: 3
    mt1:
      name: Max2 test
      password: '12345'
      person_doc_id: 6
    mt2:
      name: Max t2
      password: '1234'
      person_doc_id: 7
    tttt:
      name: tttt tttt
      password: tttt
      person_doc_id: 8
    jhubermci:
      name: Julian Huber
      password: '1234'
      person_doc_id: 9
    jvolmer:
      name: Jasper Volmer
      password: '1234'
      person_doc_id: 10
permissions:
  can_add_profile_doc_ids:
  - 4
  - 5
  - 9
  - 10
