credentials:
  usernames:
    mmustermann:
      name: Max Mustermann
      password: passwort123
      person_doc_id: 3
    admin2:
      name: Janick Hoffmann
      password: '1234'
      person_doc_id: 4
    admin1:
      name: Jakob Laurner
      password: '1234'
      person_doc_id: 5
permissions:
  can_add_profile_doc_ids:
  - 4
  - 5
